# Generated by Django 3.1.7 on 2021-03-01 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='projectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectCode', models.IntegerField(max_length=100)),
                ('projectName', models.CharField(max_length=100)),
                ('clientName', models.CharField(max_length=100)),
                ('clientEmail', models.EmailField(max_length=254)),
                ('clientPhone', models.CharField(max_length=15)),
                ('clientAddress', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
