# Generated by Django 3.1.7 on 2021-03-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='projectCode',
            field=models.IntegerField(),
        ),
    ]
