# Generated by Django 3.1.7 on 2021-03-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_matstrength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matstrength',
            name='bendStress',
            field=models.FloatField(),
        ),
    ]
