# Generated by Django 3.1.7 on 2021-03-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_sectionlibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionlibrary',
            name='ixx',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sectionlibrary',
            name='sectionName',
            field=models.CharField(default='SECTION-NAME', max_length=50),
        ),
        migrations.AddField(
            model_name='sectionlibrary',
            name='wxx',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sectionlibrary',
            name='drawing',
            field=models.ImageField(upload_to='section_pics'),
        ),
    ]
