# Generated by Django 3.1.7 on 2021-04-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_auto_20210316_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionlibrary',
            name='drawing',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
