# Generated by Django 3.1.7 on 2021-04-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_auto_20210401_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionlibrary',
            name='drawing',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
