# Generated by Django 3.1.7 on 2021-05-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_auto_20210401_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matstrength',
            name='bendStress',
            field=models.IntegerField(),
        ),
    ]
